### ISSUE TITLE
Hapi 17 support

### ISSUE THREAD

**Issue by shinzui** [atomantic/hapi-and-healthy#23]
I'm wondering if this plugin is going to be updated to support Hapi 17.

**Comment by atomantic** [comment]
starting the refactor here: https://github.com/atomantic/hapi-and-healthy/tree/hapi17

occurs to me that I need to refactor the entire route handler to be async/await since reply() is no longer something that can be called within the async library callback. I don't have a timeline for this update yet--though I welcome ideas and PR if someone wants to join as a contributor.

**Comment by atomantic** [comment]
just realized I pushed that branch from an older point (synced from another machine that was behind). Updating it now

**Comment by atomantic** [comment]
version 6.0.0 is now published to NPM. This now only supports Hapi.js 17 and above. Please report any issues. I'm doing integration validation with some services now.

**Comment by atomantic** [comment]
Note that now the test functions should be Promises not `async` lib callback functions.
